spring:
  application:
    name: ILP_CW
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      printer:
        enabled: true

logging:
  level:
    uk.ac.ed.acp.cw2.services.DroneRoutingService: DEBUG
    uk.ac.ed.acp.cw2: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

info:
  app:
    name: ILP REST Service
    description: Simple ILP Rest Service
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: never
      probes:
        enabled: false

server:
  port: 8080



ILP_ENDPOINT: https://ilp-rest-2025-bvh6e9hschfagrgy.ukwest-01.azurewebsites.net